CREATE TABLE CHARACTER (
NAME VARCHAR(20) NOT NULL PRIMARY KEY,
BIO VARCHAR(200),
PIC IMAGE,
V_ACTOR VARCHAR(20) FOREIGN KEY REFERENCES VOICE_ACTOR(NAME),
A_SHOW VARCHAR(20) FOREIGN KEY REFERENCES ANIME_SHOW(NAME),
A_MOVIE VARCHAR(20) FOREIGN KEY REFERENCES ANIME_MOVIE(NAME),
MANGA_ID VARCHAR(20) FOREIGN KEY REFERENCES MANGA(NAME),
CHARACTER_TYPE VARCHAR(10) NOT NULL,
CHECK (CHARACTER_TYPE IN ('Main', 'Side')),
)
GO

CREATE TABLE MANGA (
NAME VARCHAR(20) NOT NULL PRIMARY KEY,
DESCRIPTION VARCHAR(100),
PIC IMAGE,
AUTHOR VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES MANGA_AUTHOR(NAME),
)
GO

CREATE TABLE ANIME_SHOW (
NAME VARCHAR(20) NOT NULL PRIMARY KEY,
DESCRIPTION VARCHAR(100) NOT NULL,
PIC IMAGE,
STUDIO VARCHAR(10) NOT NULL,
MANGA_ID VARCHAR(20) FOREIGN KEY REFERENCES MANGA(NAME),
)
GO

CREATE TABLE ANIME_MOVIE (
NAME VARCHAR(20) NOT NULL PRIMARY KEY,
DESCRIPTION VARCHAR(100) NOT NULL,
PIC IMAGE,
STUDIO VARCHAR(10) NOT NULL,
MANGA VARCHAR(20) FOREIGN KEY REFERENCES MANGA(NAME),
)
GO

CREATE TABLE VOICE_ACTOR (
NAME VARCHAR(20) NOT NULL PRIMARY KEY,
BIO VARCHAR(100),
CHARACTER_PLAYED VARCHAR(20) FOREIGN KEY REFERENCES character(NAME),
A_SHOW VARCHAR(20) FOREIGN KEY REFERENCES ANIME_SHOW(NAME),
A_MOVIE VARCHAR(20) FOREIGN KEY REFERENCES ANIME_MOVIE(NAME)
)
GO

CREATE TABLE MANGA_AUTHOR (
NAME VARCHAR (20) NOT NULL PRIMARY KEY,
MANGA_ID VARCHAR(20) FOREIGN KEY REFERENCES MANGA(NAME),
PIC IMAGE
)
GO

CREATE TABLE STAFF_MEMBERS (
NAME VARCHAR(100) NOT NULL PRIMARY KEY,
ROLE VARCHAR(100),
A_SHOW VARCHAR(20) FOREIGN KEY REFERENCES ANIME_SHOW(NAME),
A_MOVIE VARCHAR(20) FOREIGN KEY REFERENCES ANIME_MOVIE(NAME),
STUDIO VARCHAR(20)
)
GO